#配置环境：application.yml、application-local.yml、application-dev.yml、application-test.yml、application-pre.yml、application-product.yml
server:
  port: 8022

#localhost 127.0.0.1
spring:
  application:
    name: springboot20-community
  datasource:
    wong:
      jdbc-url: jdbc:mysql://localhost:3306/wong_user?characterEncoding=utf8&serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver
      name: wong_user
      username: root
      password: 123456
    yoong:
      jdbc-url: jdbc:mysql://localhost:3306/yoong_business?characterEncoding=utf8&serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver
      name: yoong_business
      username: root
      password: 123456
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect

#SpringBoot 2.0 Actuator配置
#访问：http://127.0.0.1:8080/actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'

