#配置环境：application.yml、application-local.yml、application-dev.yml、application-test.yml、application-pre.yml、application-product.yml
server:
  port: 8081

#localhost 127.0.0.1
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wong_user?characterEncoding=utf8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: wong_user
    username: root
    password: 123456
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect

#Actuator: auditevents,beans,caches,conditions,configprops,env,flyway,health,info,liquibase,metrics,mappings,scheduledtasks,sessions,shutdown,threaddump,httptrace
#版本：<springboot.version>1.5.10.RELEASE</springboot.version>
#访问：http://127.0.0.1:8080/beans
#management:
#  port: 8080
#  security:
#    enabled: false

#Actuator: auditevents,beans,caches,conditions,configprops,env,flyway,health,info,liquibase,metrics,mappings,scheduledtasks,sessions,shutdown,threaddump,httptrace
#不可访问: flyway,liquibase,sessions,shutdown
#版本：<springboot.version>2.0.0.RELEASE</springboot.version>，需引用插件
#访问：http://127.0.0.1:8080/actuator/info
#访问：http://127.0.0.1:8080/actuator/beans
#management:
#  endpoints:
#    web:
#      exposure:
#        include: *

