#配置环境：application.yml、application-local.yml、application-dev.yml、application-test.yml、application-pre.yml、application-product.yml
server:
  port: 8011

#localhost 127.0.0.1
spring:
  application:
    name: springboot-accidence
  datasource:
    url: jdbc:mysql://localhost:3306/wong_user?characterEncoding=utf8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: wong_user
    username: root
    password: 123456
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect

#SpringBoot 2.0 Actuator配置
#访问：http://127.0.0.1:8080/actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'

