server:
  port: 8090

spring:
  application:
    name: springboot-dist
  datasource:
    a1902biz:
      url: jdbc:mysql://127.0.0.1:3306/a1902_biz?serverTimezone=UTC&useSSL=false
      username: root
      password: 123456
      driverClassName: com.mysql.cj.jdbc.Driver
    a1902stage:
      url: jdbc:mysql://127.0.0.1:3306/a1902_stage?serverTimezone=UTC&useSSL=false
      username: root
      password: 123456
      driverClassName: com.mysql.cj.jdbc.Driver
    wonguser:
      url: jdbc:mysql://127.0.0.1:3306/wong_user?serverTimezone=UTC&useSSL=false
      username: root
      password: 123456
      driverClassName: com.mysql.cj.jdbc.Driver

dubbo:
  dist:
    address: zookeeper://127.0.0.1:2181
    group: dev
    version: 1.0